### ISSUE TITLE
#<RestClient::BadRequest: 400 Bad Request>

### ISSUE THREAD

**Issue by jmesserer** [joshnesbitt/google_url_shortener#11]
➜  abc git:(master): ruby -v
ruby 2.2.6p322 (2016-04-29 revision 54815) [x86_64-darwin15]

➜  abc git:(master): rails -v
Rails 5.0.2

➜  abc git:(master): gem -v
2.6.4

➜  abc git:(master): bundler -v
Bundler version 1.14.6

➜  abc git:(master): gem list google_url_shortener
*** LOCAL GEMS ***
google_url_shortener (1.1.0)

➜  abc git:(master): rails c
 :009 > t = 'https://mdbootstrap.com/components/inputs'
 => "https://mdbootstrap.com/components/inputs"

 :010 > st = Google::UrlShortener.shorten! t
RestClient.post "https://www.googleapis.com/urlshortener/v1/url?key=xxxxxxxxxxxxxxxxxxxxx", "{\"longUrl\":\"https://mdbootstrap.com/components/inputs\"}", "Accept"=>"application/json", "Accept-Encoding"=>"gzip, deflate", "Content-Length"=>"55", "Content-Type"=>"application/json", "User-Agent"=>"rest-client/2.0.2 (darwin15.5.0 x86_64) ruby/2.2.6p322"
# => 400 BadRequest | application/json 132 bytes
#<RestClient::BadRequest: 400 Bad Request>
NoMethodError: undefined method `[]' for nil:NilClass
	from /Users/jdm/.rvm/gems/ruby-2.2-head@abc/gems/google_url_shortener-1.1.0/lib/google/url_shortener/url.rb:27:in `encode!'
	from /Users/jdm/.rvm/gems/ruby-2.2-head@abc/gems/google_url_shortener-1.1.0/lib/google/url_shortener.rb:13:in `shorten!'
	from (irb):10
	from /Users/jdm/.rvm/gems/ruby-2.2-head@abc/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /Users/jdm/.rvm/gems/ruby-2.2-head@abc/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/jdm/.rvm/gems/ruby-2.2-head@abc/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/jdm/.rvm/gems/ruby-2.2-head@abc/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/jdm/.rvm/gems/ruby-2.2-head@abc/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by bf4** [comment]
would be nice to have an error handler rather than always raising, or at least get a better exception..

**Comment by joshnesbitt** [comment]
Agree completely. I think there are a few nice additions that would make the DSL a bit easier to deal with, happy to accept a PR for this but I'm afraid I don't have time to work on this for now 😢

**Comment by darkfishy** [comment]
Could this error be related to a recent [announcement by Google](https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html)? 
On using `shorten!` method, I get instead:

```ruby
#<RestClient::Forbidden: 403 Forbidden>
NoMethodError: undefined method `[]' for nil:NilClass
from /Users/devuser/.rvm/gems/ruby-2.3.0@wbcl12/gems/google_url_shortener-1.1.0/lib/google/url_shortener/url.rb:27:in `encode!'
```

**Comment by joshnesbitt** [comment]
Absolutely, looks like this gem may become less useful...

**Comment by darkfishy** [comment]
@joshnesbitt First of all, my apologies that I haven't looked deeply into your code, hence this question.
How difficult would it be to change the underlying REST call from Shortener API to [this Firebase API](https://firebase.google.com/docs/dynamic-links/rest)
Even more so, would it be worth it?

**Comment by joshnesbitt** [comment]
I guess you could look at an approach similar to [this gem](https://github.com/robbyrussell/shorturl) that supports multiple backends. The gem itself is pretty simple so as long as there was a single request to shorten a URL it would be relatively easy.

**Comment by darkfishy** [comment]
I started looking more into Firebase, but unfortunately it is not a viable option for just short links. It needs an app to be created, which could either be an iOS or an Android app. So not particularly useful for web apps.
Thanks again Josh for a wonderful gem, pun intended. I will have a look at your suggestion.

**Comment by joshnesbitt** [comment]
Thank you @darkfishy.

**Comment by sahilchopra** [comment]
Any luck with this? Can you please suggest some alternative.

**Comment by joshnesbitt** [comment]
I don't have an alternative I'm afraid, might be worth looking at other URL shortener services and seeing if they provide Ruby integrations...

**Comment by sahilchopra** [comment]
Thanks for your quick response. I switch to https://github.com/robbyrussell/shorturl 

Thanks for your wonderful library. I used it for 2 years.

**Comment by joshnesbitt** [comment]
Thank you 😄
